// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class Address
{
    public int IdAddress { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string Building { get; set; }

    public string Corpus { get; set; }

    public string Office { get; set; }

    public virtual ICollection<Object> Objects { get; set; } = new List<Object>();
}