// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class Employee
{
    public int IdEmployee { get; set; }

    public int? IdFullname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Experience { get; set; }

    public string Metro { get; set; }

    public string Schedules { get; set; }

    public string Notes { get; set; }

    public string Comments { get; set; }

    public DateOnly? HireDate { get; set; }

    public decimal? Salary { get; set; }

    public byte[] PhoneEnc { get; set; }

    public byte[] EmailEnc { get; set; }

    public byte[] PhoneEncrypted { get; set; }

    public byte[] EmailEncrypted { get; set; }

    public virtual Fullname IdFullnameNavigation { get; set; }

    public virtual ICollection<WorkSchedule> WorkSchedules { get; set; } = new List<WorkSchedule>();
}