// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class Fullname
{
    public int IdFullname { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public byte[] LastNameEnc { get; set; }

    public byte[] FirstNameEnc { get; set; }

    public byte[] MiddleNameEnc { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}