// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class Object
{
    public int IdObject { get; set; }

    public int IdAddress { get; set; }

    public string ObjectName { get; set; }

    public virtual Address IdAddressNavigation { get; set; }

    public virtual ICollection<Rate> Rates { get; set; } = new List<Rate>();
}