// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class Rate
{
    public int IdRate { get; set; }

    public int IdObject { get; set; }

    public int IdService { get; set; }

    public decimal HourlyRate { get; set; }

    public virtual Object IdObjectNavigation { get; set; }

    public virtual Service IdServiceNavigation { get; set; }

    public virtual ICollection<WorkSchedule> WorkSchedules { get; set; } = new List<WorkSchedule>();
}