// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiplomProject.Models;

public partial class WorkSchedule
{
    public int IdSchedule { get; set; }

    public int IdEmployee { get; set; }

    public int IdRate { get; set; }

    public DateOnly? WorkDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public decimal? DailyHours { get; set; }

    public int? TotalDays { get; set; }

    public decimal? TotalHours { get; set; }

    public string Notes { get; set; }

    public DateTime? RecordCreated { get; set; }

    public virtual Employee IdEmployeeNavigation { get; set; }

    public virtual Rate IdRateNavigation { get; set; }
}